# Generated by Django 3.2.3 on 2021-05-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_name_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='average_review',
            field=models.IntegerField(default=0),
        ),
    ]
