# Generated by Django 3.2.3 on 2021-05-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content_rating',
        ),
        migrations.RemoveField(
            model_name='project',
            name='design_rating',
        ),
        migrations.RemoveField(
            model_name='project',
            name='usability_rating',
        ),
        migrations.AddField(
            model_name='project',
            name='content_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='design_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='usability_rate',
            field=models.IntegerField(default=0),
        ),
    ]
